nelmio_cors:
  defaults:
    origin_regex: true
    allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
    allow_headers: ['Content-Type','Authorization']
    allow_methods: ['GET','OPTIONS','POST','PUT','PATCH','DELETE']
    max_age: 3600
  paths:
    '^/':
